---
title: "manuscript_subsampling"
author: "Jenna Hershberger"
date: "2021-02-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction
Prior to this script, run server_subsampling_generalized.R and server_subsample_plsr.R. Then convert the output Rds to a df.

```{r}
library(tidyverse)
library(ggpubr)
library(magrittr)

iwanthue <- c("#c84d4c","#c77c3f","#d19f32","#647e3a","#61b858","#4db5a4","#6585cc","#975fc7","#c575a1","#cf4391")
namekey <- read.csv("data/TrialNameKey.csv") %>% rename(Trial = Abbreviated.Trial.Name) 
```


```{r}
subsamp_input <- read.csv("output/subsampling_prediction_results_2021.csv") %>%
  full_join(namekey) %>% 
    mutate(`Subsample type` = case_when(
        str_detect(studyName, "19.") ~ "Homogenized sample",
        !str_detect(studyName, "19.") & str_detect(studyName, "UYT") ~ "Homogenized sample",
        !str_detect(studyName, "19.") & !str_detect(studyName, "UYT") ~ "Roots"),
      num_samp_fct = as.factor(number_samples)) 

subsamp_input %>% group_by(studyName) %>% summarize(max(number_samples))
```

```{r}
subsample.df <- subsamp_input %>%
  filter(`Subsample type` == "Homogenized sample") %>%
  drop_na() %>%
  mutate(num_samp_fct = fct_reorder(num_samp_fct, number_samples)) 

subsample_plot <- subsample.df %>%
  ggplot(aes(x = num_samp_fct, y = R2p, fill = Trial)) +
  geom_boxplot() + facet_grid(cols = vars(Trial)) + theme_bw() +
  scale_fill_manual(values = iwanthue[c(4:10)], name = "Trial") +
  coord_cartesian(ylim = c(0, 1)) + 
  labs(fill = "Trial", x = "Number of samples", y = expression("R"["p"]^2)) + #,
       #title = expression(paste("IITA ", "R"["p"]^2, " by number of homogenized samples per plot")),
       #subtitle = "50 iterations of scan subsampling within plots followed by PLSR of DMC with 10 iterations of waves pipeline") +
  theme(legend.position = "none") #strip.background = element_blank(), strip.text.y = element_blank())
subsample_plot

root_plot <- subsamp_input %>%
  filter(`Subsample type` == "Roots") %>%
  drop_na() %>%
  mutate(num_samp_fct = fct_reorder(num_samp_fct, number_samples)) %>%
  ggplot(aes(x = num_samp_fct, y = R2p, fill = Trial)) +
  geom_boxplot() + facet_grid(cols = vars(Trial)) + theme_bw() +
  scale_fill_manual(values = iwanthue[c(1:3)], name = "Trial") +
  coord_cartesian(ylim = c(0, 1)) + 
  labs(fill = "Trial", x = "Number of roots", y = expression("R"["p"]^2))+#,
       #title = expression(paste("IITA ", "R"["p"]^2, " by number of roots sampled per plot")),
       #subtitle = "50 iterations of scan subsampling within plots followed by PLSR of DMC with 10 iterations of waves pipeline")#+
  # theme(#strip.background = element_blank(),
  #       strip.text.y = element_blank())
  theme(legend.position = "none")
root_plot

split.fig <- ggarrange(root_plot, subsample_plot,
                          labels = c("A", "B"),
                          nrow = 2,
                          widths = c(0.6, 1))
split.fig
```

```{r}
ggsave(plot = split.fig, filename = "output/Figure5_Subsamples.png",
       units = "in", height = 9, width = 12)
```
